version: 2.1
orbs:
  snyk: snyk/snyk@2.1.0

jobs:
  snyk-scan:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn install
      - snyk/scan

workflows:
  build-test-snyk:
    jobs: 
      - snyk-scan
