version: 2.1
orbs:
  snyk: snyk/snyk@2.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/open:jdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean pacakge
      - run:
          name: Test
          command: mvn test
  snyk-scan:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - run:
          name: Install Snyk to HTML
          command: npm install --prefix=$HOME/.local -g snyk-to-html
      - snyk/scan:
          monitor-on-build: false
          fail-on-issues: false
          command: code test
          additional-arguments: --all-proejcts --json-file-output=code-results.json
      - run:
          name: Generate Snyk HTML report
          command: cat code-results.json | snyk-to-html -o code-report.html 
      - store_artifacts:
          paht: code-report.html

workflows:
  build-test-snyk:
      jobs:
        - build-and-test
        - snyk-scan
          
