name: Java CI with Maven

on: workflow_dispatch
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn install

    - name: set up snyk
      run: |
        sudo npm install snyk -g
        sudo npm install npm install -g snyk-delta
        ls -la
        cd todolist-goof
        docker build -t todolist-goof:latest .
        snyk auth ${{secrets.SNYK_TOKEN}}
